In [51]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [52]:
df = pd.read_excel(r"C:\Users\ASUS\Documents\jewellery_sales_report.xlsx")
df

,Date,Invoice No,Customer Name,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Cost Amount,Salesperson,Branch
0,2025-02-21,INV10000,Cust_1466,Gold,Rings,3,8.64,129879,106465.933054,Rahul,Delhi
1,2025-03-29,INV10001,Cust_7949,Gold,Necklaces,4,3.76,26023,21603.714146,Priya,Bangalore
2,2025-03-01,INV10002,Cust_9666,Gold,Chains,4,22.17,95305,76715.882343,Rahul,Delhi
3,2025-02-11,INV10003,Cust_4005,Platinum,Bands,4,5.44,133855,99930.021555,Rahul,Bangalore
4,2025-02-24,INV10004,Cust_6393,Platinum,Bands,1,34.34,21394,18655.313012,Sneha,Chennai
...,...,...,...,...,...,...,...,...,...,...,...
495,2025-02-19,INV10495,Cust_7628,Silver,Rings,2,14.16,166410,132099.826198,Sneha,Delhi
496,2025-02-06,INV10496,Cust_7026,Diamond,Rings,4,8.62,195639,137287.952381,Karan,Mumbai
497,2025-02-25,INV10497,Cust_5131,Platinum,Bands,3,15.82,156480,120605.291503,Karan,Mumbai
498,2025-03-27,INV10498,Cust_8542,Platinum,Rings,2,8.59,22453,19599.937354,Rahul,Bangalore
499,2025-02-15,INV10499,Cust_7381,Platinum,Bands,1,25.77,188367,153733.808892,Rahul,Bangalore

In [53]:
df.drop(columns=['Date','Invoice No','Customer Name','Cost Amount','Salesperson'],inplace=True)

In [54]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch
0,Gold,Rings,3,8.64,129879,Delhi
1,Gold,Necklaces,4,3.76,26023,Bangalore
2,Gold,Chains,4,22.17,95305,Delhi
3,Platinum,Bands,4,5.44,133855,Bangalore
4,Platinum,Bands,1,34.34,21394,Chennai
...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi
496,Diamond,Rings,4,8.62,195639,Mumbai
497,Platinum,Bands,3,15.82,156480,Mumbai
498,Platinum,Rings,2,8.59,22453,Bangalore
499,Platinum,Bands,1,25.77,188367,Bangalore

In [55]:
df["Pieces %"] = df['Quantity Sold'].apply(lambda x:x/df['Quantity Sold'].sum()*100)

In [56]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %
0,Gold,Rings,3,8.64,129879,Delhi,0.242718
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.323625
2,Gold,Chains,4,22.17,95305,Delhi,0.323625
3,Platinum,Bands,4,5.44,133855,Bangalore,0.323625
4,Platinum,Bands,1,34.34,21394,Chennai,0.080906
...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.161812
496,Diamond,Rings,4,8.62,195639,Mumbai,0.323625
497,Platinum,Bands,3,15.82,156480,Mumbai,0.242718
498,Platinum,Rings,2,8.59,22453,Bangalore,0.161812
499,Platinum,Bands,1,25.77,188367,Bangalore,0.080906

In [57]:
df['Pieces %'] = df['Pieces %'].apply(lambda x: f"{x:.2f}")

In [58]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %
0,Gold,Rings,3,8.64,129879,Delhi,0.24
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32
2,Gold,Chains,4,22.17,95305,Delhi,0.32
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32
4,Platinum,Bands,1,34.34,21394,Chennai,0.08
...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08

In [59]:
df['Wt %'] = df['Weight (g/carat)'].apply(lambda x: x/df['Weight (g/carat)'].sum()*100)

In [60]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %,Wt %
0,Gold,Rings,3,8.64,129879,Delhi,0.24,0.069104
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32,0.030073
2,Gold,Chains,4,22.17,95305,Delhi,0.32,0.177320
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32,0.043510
4,Platinum,Bands,1,34.34,21394,Chennai,0.08,0.274658
...,...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16,0.113254
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32,0.068944
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24,0.126531
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16,0.068705
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08,0.206114

In [61]:
df['Wt %'] = df['Wt %'].apply(lambda x: f"{x:.2f}")

In [62]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %,Wt %
0,Gold,Rings,3,8.64,129879,Delhi,0.24,0.07
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32,0.03
2,Gold,Chains,4,22.17,95305,Delhi,0.32,0.18
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32,0.04
4,Platinum,Bands,1,34.34,21394,Chennai,0.08,0.27
...,...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16,0.11
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32,0.07
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24,0.13
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16,0.07
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08,0.21

In [63]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity Sold,500.0,2.47200,1.143605,1.00,1.00,2.500,3.2500,4.00
Weight (g/carat),500.0,25.00564,14.524279,1.02,12.66,24.505,37.2925,49.92
Sales Amount,500.0,105980.48600,54002.599482,11283.00,61299.50,105539.000,154369.0000,198856.00

In [64]:
df.dtypes

Category             object
Sub-Category         object
Quantity Sold         int64
Weight (g/carat)    float64
Sales Amount          int64
Branch               object
Pieces %             object
Wt %                 object
dtype: object

In [65]:
df['Wt %'] = df['Wt %'].astype(float)

In [66]:
df['Pieces %'] = df['Pieces %'].astype(float)

In [67]:
df.dtypes

Category             object
Sub-Category         object
Quantity Sold         int64
Weight (g/carat)    float64
Sales Amount          int64
Branch               object
Pieces %            float64
Wt %                float64
dtype: object

In [68]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity Sold,500.0,2.47200,1.143605,1.00,1.00,2.500,3.2500,4.00
Weight (g/carat),500.0,25.00564,14.524279,1.02,12.66,24.505,37.2925,49.92
Sales Amount,500.0,105980.48600,54002.599482,11283.00,61299.50,105539.000,154369.0000,198856.00
Pieces %,500.0,0.19776,0.091488,0.08,0.08,0.200,0.2600,0.32
Wt %,500.0,0.20012,0.116416,0.01,0.10,0.200,0.3000,0.40

In [69]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %,Wt %
0,Gold,Rings,3,8.64,129879,Delhi,0.24,0.07
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32,0.03
2,Gold,Chains,4,22.17,95305,Delhi,0.32,0.18
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32,0.04
4,Platinum,Bands,1,34.34,21394,Chennai,0.08,0.27
...,...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16,0.11
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32,0.07
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24,0.13
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16,0.07
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08,0.21

In [70]:
df.loc[:,'Pieces %']

0      0.24
1      0.32
2      0.32
3      0.32
4      0.08
       ...
495    0.16
496    0.32
497    0.24
498    0.16
499    0.08
Name: Pieces %, Length: 500, dtype: float64

In [71]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %,Wt %
0,Gold,Rings,3,8.64,129879,Delhi,0.24,0.07
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32,0.03
2,Gold,Chains,4,22.17,95305,Delhi,0.32,0.18
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32,0.04
4,Platinum,Bands,1,34.34,21394,Chennai,0.08,0.27
...,...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16,0.11
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32,0.07
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24,0.13
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16,0.07
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08,0.21

In [72]:
summary = df.groupby('Sub-Category')['Weight (g/carat)'].agg(Mean = 'mean',Std = 'std')

In [73]:
summary

                   Mean        Std
Sub-Category
Anklets       25.270893  16.502245
Bands         22.991311  13.334299
Bangles       26.019737  12.455197
Chains        25.395455  12.493369
Earrings      24.587609  15.502684
Necklaces     27.206250  13.648195
Pendants      26.000789  14.565612
Rings         24.739734  15.059258

In [74]:
summary['CV'] = summary['Std']/summary['Mean']

In [75]:
summary

                   Mean        Std        CV
Sub-Category
Anklets       25.270893  16.502245  0.653014
Bands         22.991311  13.334299  0.579971
Bangles       26.019737  12.455197  0.478683
Chains        25.395455  12.493369  0.491953
Earrings      24.587609  15.502684  0.630508
Necklaces     27.206250  13.648195  0.501657
Pendants      26.000789  14.565612  0.560199
Rings         24.739734  15.059258  0.608707

In [76]:
df = pd.merge(df,summary,on='Sub-Category',how='left')
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %,Wt %,Mean,Std,CV
0,Gold,Rings,3,8.64,129879,Delhi,0.24,0.07,24.739734,15.059258,0.608707
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32,0.03,27.206250,13.648195,0.501657
2,Gold,Chains,4,22.17,95305,Delhi,0.32,0.18,25.395455,12.493369,0.491953
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32,0.04,22.991311,13.334299,0.579971
4,Platinum,Bands,1,34.34,21394,Chennai,0.08,0.27,22.991311,13.334299,0.579971
...,...,...,...,...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16,0.11,24.739734,15.059258,0.608707
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32,0.07,24.739734,15.059258,0.608707
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24,0.13,22.991311,13.334299,0.579971
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16,0.07,24.739734,15.059258,0.608707
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08,0.21,22.991311,13.334299,0.579971

In [77]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity Sold,500.0,2.472000,1.143605,1.000000,1.000000,2.500000,3.250000,4.000000
Weight (g/carat),500.0,25.005640,14.524279,1.020000,12.660000,24.505000,37.292500,49.920000
Sales Amount,500.0,105980.486000,54002.599482,11283.000000,61299.500000,105539.000000,154369.000000,198856.000000
Pieces %,500.0,0.197760,0.091488,0.080000,0.080000,0.200000,0.260000,0.320000
Wt %,500.0,0.200120,0.116416,0.010000,0.100000,0.200000,0.300000,0.400000
Mean,500.0,25.005640,1.048152,22.991311,24.739734,24.739734,25.395455,27.206250
Std,500.0,14.533563,1.211855,12.455197,13.334299,15.059258,15.059258,16.502245
CV,500.0,0.582331,0.054357,0.478683,0.560199,0.608707,0.608707,0.653014

In [78]:
High_mean = df['Mean'].max()
High_mean

27.20625

In [79]:
low_cv = df['CV'].min()

In [80]:
low_cv

0.4786826577338209

In [81]:
medium_mean = df['Mean'].quantile(0.5)
medium_mean

24.73973404255319

In [82]:
medium_cv = df['CV'].quantile(0.5)
medium_cv

0.6087073668144121

In [83]:
low_mean = df['Mean'].min()

In [84]:
low_mean

22.991311475409837

In [85]:
high_cv = df['CV'].max()
high_cv

0.6530139299040643

In [86]:
def classify(row,High_mean,medium_mean,low_cv,medium_cv):
    if row['Mean'] >= High_mean and row['CV'] <= low_cv:  # high & consistent
        return 'Fast'
    elif row['Mean'] >= medium_mean and row['CV'] <= medium_cv:
        return 'Normal'
    else:
        return 'Slow'

In [87]:
df['Rank'] = df.apply(classify,axis=1,High_mean= High_mean,medium_mean=medium_mean,low_cv=low_cv,medium_cv=medium_cv)

In [88]:
df

,Category,Sub-Category,Quantity Sold,Weight (g/carat),Sales Amount,Branch,Pieces %,Wt %,Mean,Std,CV,Rank
0,Gold,Rings,3,8.64,129879,Delhi,0.24,0.07,24.739734,15.059258,0.608707,Normal
1,Gold,Necklaces,4,3.76,26023,Bangalore,0.32,0.03,27.206250,13.648195,0.501657,Normal
2,Gold,Chains,4,22.17,95305,Delhi,0.32,0.18,25.395455,12.493369,0.491953,Normal
3,Platinum,Bands,4,5.44,133855,Bangalore,0.32,0.04,22.991311,13.334299,0.579971,Slow
4,Platinum,Bands,1,34.34,21394,Chennai,0.08,0.27,22.991311,13.334299,0.579971,Slow
...,...,...,...,...,...,...,...,...,...,...,...,...
495,Silver,Rings,2,14.16,166410,Delhi,0.16,0.11,24.739734,15.059258,0.608707,Normal
496,Diamond,Rings,4,8.62,195639,Mumbai,0.32,0.07,24.739734,15.059258,0.608707,Normal
497,Platinum,Bands,3,15.82,156480,Mumbai,0.24,0.13,22.991311,13.334299,0.579971,Slow
498,Platinum,Rings,2,8.59,22453,Bangalore,0.16,0.07,24.739734,15.059258,0.608707,Normal
499,Platinum,Bands,1,25.77,188367,Bangalore,0.08,0.21,22.991311,13.334299,0.579971,Slow